# Note:
# The Raspberry Pi machine need to setup SSH for the server to upload image.
# Set environment variable $FULL_BUILD to build from stage0.

steps:
  - label: "Config :spiral_note_pad: and run :building_construction: build.sh"
    commands:
      - echo "IMG_NAME='SUSIbian'" > config
      - touch ./stage3/SKIP ./stage4/SKIP
      - touch ./stage2/SKIP_IMAGES ./stage4/SKIP_IMAGES
      - echo -e "\nAPT_PROXY=http://localhost:3142" >> config
      - echo -e "\nWORK_DIR=$(realpath $PWD/../Work)" >> config
      - echo -e "\nDEPLOY_DIR=$(realpath $PWD/../Deploy)" >> config
      - sudo rm -rf "$(realpath $PWD/../Work/stage2.5)"
      - sudo rm -rf "$(realpath $PWD/../Work/export-image)"
      - sudo rm -rf "$(realpath $PWD/../Deploy)"
      - if [ "$FULL_BUILD" ]; then sudo rm -rf $(realpath $PWD/../Work); else touch ./stage0/SKIP ./stage1/SKIP ./stage2/SKIP; fi
      - if [ "$FULL_BUILD" ]; then sudo ./build.sh; else sudo CLEAN=1 ./build.sh; fi
  - wait
  - label: "Upload :truck: image file"
    commands:
      - ./.buildkite/upload_image.sh "img-storage" "~/Softwares/SUSI.AI-Image/"
