steps:
  - labels: Add config and run build.sh
    commands:
      - echo "IMG_NAME='SUSIbian'" > config
      - touch ./stage3/SKIP ./stage4/SKIP
      - touch ./stage2/SKIP_IMAGES ./stage4/SKIP_IMAGES
      - echo -e "\nAPT_PROXY=http://localhost:3142" >> config
      - echo -e "\nWORK_DIR=$(realpath $PWD/../Work)" >> config
      - echo -e "\nDEPLOY_DIR=$(realpath $PWD/../Deploy)" >> config
      - sudo rm -rf $(realpath $PWD/../Work/stage2.5)
      - sudo rm -rf $(realpath $PWD/../Deploy)
      - if [ "$CONTINUE" ]; then touch ./stage0/SKIP ./stage1/SKIP; fi
      - if [ "$CONTINUE" ]; then sudo CLEAN=1 ./build.sh; else sudo ./build.sh; fi
